# Generated by Django 5.2.16 on 2026-07-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_color', models.CharField(blank=True, default='bg-stone-50', help_text='Tailwind CSS background class for category card (e.g. bg-stone-50)', max_length=50)),
                ('icon', models.CharField(blank=True, default='Sparkles', help_text='Lucide icon name for category card (e.g. Cake, Heart, Sparkles)', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('template_type', models.CharField(choices=[('canva_template', 'Canva Template'), ('custom_website', 'Custom Website')], db_index=True, default='canva_template', max_length=20)),
                ('thumbnail', models.URLField(blank=True, default='', help_text='External URL for template thumbnail image', max_length=500)),
                ('preview_url', models.URLField(blank=True, default='', help_text='URL for live preview or demo', max_length=500)),
                ('canva_url', models.URLField(blank=True, default='', help_text='Canva editor link (for canva_template type only)', max_length=500)),
                ('ratio', models.CharField(blank=True, default='', help_text='Layout ratio descriptor (e.g. A4 Layout, 16:9 Landscape)', max_length=100)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Show in Featured Templates section')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active templates are publicly visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='templates_app.category')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='templates_a_categor_5fa7a2_idx'), models.Index(fields=['template_type', 'is_active'], name='templates_a_templat_168b2c_idx')],
            },
        ),
    ]
